version: '3.9'

services:
  autossh-server:
    container_name: autossh-server
    build:
      dockerfile: ./autossh/Dockerfile
      context: ./
    restart: unless-stopped
    # tty: true
    # ports:
    #   - "1337:1337"

  proxy-server:
    container_name: proxy-server
    build: ./privoxy
    restart: unless-stopped
    ports:
      - "8118:8118"
    volumes:
      - ./config/whitelist.action:/etc/privoxy/whitelist.action